//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PDUApp.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_STR_PDU_HEADER_NM           101
#define IDS_STR_VOLTAGE_HEADER_NM       102
#define IDS_STR_CURRENT_HEADER_NM       103
#define IDS_STR_POWER_FACTOR_HEADER_NM  104
#define IDS_STR_CREST_FACTOR_HEADER_NM  105
#define IDS_STR_FREQ_HEADER_NM          106
#define IDS_STR_REAL_POWER_HEADER_NM    107
#define IDS_STR_NO_MEM                  108
#define IDS_STR_PDU_NM                  109
#define IDS_STR_NO_PDU_MESS             110
#define IDS_STR_BANK_NM                 111
#define IDS_STR_OUTLET_NM               112
#define IDS_STR_APP_TITLE               113
#define IDS_STR_OUTLET_NM_CHECK         114
#define IDS_STR_SEL_OUTLET_RELAY_MESS   115
#define IDS_STR_SEL_OUTLET_RELAY_ERR    116
#define IDS_STR_ON                      117
#define IDS_STR_OFF                     118
#define IDS_STR_REBOOT                  119
#define IDS_STR_REBOOTED                120
#define IDS_STR_SEL_OUTLET_ERR          121
#define IDS_STR_APPR_POWER_HEADER_NM    122
#define IDS_STR_WND_HAN_GET_FAIL        123
#define IDS_STR_POLL_CONF               124
#define IDS_STR_POLL_INTER              125
#define IDS_STR_SECS                    126
#define IDS_STR_SET                     127
#define IDR_MAINFRAME                   128
#define IDS_STR_START                   129
#define IDD_DLG_RIGHT                   130
#define IDB_BITMAP1                     130
#define IDS_STR_STOP                    130
#define IDB_BITMAP2                     131
#define IDS_STR_MIN_POLL_SEC_GRT_5SECS_MESS 131
#define IDD_SPLASH                      132
#define IDS_STR_MAX_POLL_SEC            132
#define IDB_SPLASH                      133
#define IDS_STR_BG_TEXT                 133
#define IDD_DLG_ALERT                   133
#define IDR_MENU_OUTLET_LED             134
#define IDS_STR_PDU_DEV_NM_CHECK        134
#define IDD_DLG_STATIC_INFO             134
#define IDS_STR_BANK_NM_CHECK           135
#define IDI_ICON_GRAY                   135
#define IDS_STR_CURR_NM                 136
#define IDI_ICON_GREEN                  136
#define IDS_STR_VOLT_NM                 137
#define IDI_ICON_RED                    137
#define IDS_STR_FREQ_NM                 138
#define IDI_ICON_BANK                   138
#define IDS_STR_APP_POW_NM              139
#define IDS_STR_REAL_POW_NM             140
#define IDI_ICON_PDU                    140
#define IDS_STR_POW_FAC_NM              141
#define IDR_MENU_LOG                    141
#define IDS_STR_MODEL_NM                142
#define IDI_ICON_ERROR                  142
#define IDS_STR_MODEL_NUM               143
#define IDI_ICON_HIGH                   143
#define IDS_STR_SERIAL_NUM              144
#define IDI_ICON3                       144
#define IDI_ICON_LOW                    144
#define IDS_STR_FIRM_VERS               145
#define IDI_ICON_WARN                   145
#define IDS_STR_UNABLE_GET_STATIC_ERR_MESS 146
#define IDI_ICON_CRIC                   146
#define IDS_STR_VCB_NM                  147
#define IDI_ICON_PASS                   147
#define IDS_STR_ENABLED                 148
#define IDS_STR_THRESHOLD               149
#define IDD_ALERT_POPUP                 149
#define IDS_STR_HIGH_CURR_ALRT          150
#define IDB_BITMAP3                     150
#define IDB_BITMAP_PPW                  150
#define IDS_STR_LOW_CURR_ALRT           151
#define IDS_STR_ALERT_CONF              152
#define IDS_STR_A                       153
#define IDS_STR_MAX_GRC_PER             154
#define IDS_STR_SEC                     155
#define IDS_STR_DLG_STATIC_INFO         156
#define IDS_STR_EXIT                    157
#define IDS_STR_HIGH_CURR_MESS          158
#define IDS_STR_LOW_CURR_MESS           159
#define IDS_STR_NO_BANK_OUTLET_MESS     160
#define IDS_STR_ZERO_BANK_OUTLET_MESS   161
#define IDS_STR_FETCH_OUTLET_DATA_ERR   162
#define IDS_STR_SER_NUM_ERR             163
#define IDS_STR_COPY_TXT                164
#define IDC_PIC_SPLASH                  1000
#define IDC_STATIC_LOG                  1000
#define IDC_STATIC_CURRENT1             1001
#define IDC_STATIC_VOLTAGE              1001
#define IDC_STATIC_CURRENT              1002
#define IDC_STATIC_FREQ                 1003
#define IDC_STATIC_APPPOWER             1004
#define IDC_STATIC_REALPOWER            1005
#define IDC_STATIC_POWFAC               1006
#define IDC_ST_CURR_VAL                 1007
#define IDC_ST_VOL_VAL                  1008
#define IDC_ST_FREQ_VAL                 1009
#define IDC_ST_APPPOW_VAL               1010
#define IDC_ST_REALPOW_VAL              1011
#define IDC_ST_POWFAC_VAL               1012
#define IDC_STATIC_POLL_CONF            1014
#define IDC_STATIC_POLL                 1015
#define IDC_EDIT_SECS                   1016
#define IDC_STATIC_SECS                 1017
#define IDC_BUT_SET                     1018
#define IDC_BUT_START_STOP              1019
#define IDC_STATIC_OUTLET_VAL           1020
#define IDC_STATIC_BG_TEXT              1021
#define IDC_FRAME_VIR_CIR_BRK           1023
#define IDC_CHK_VIR_CIR_BRK_ENB         1024
#define IDC_STATIC_THRES_HOLD_VCB       1025
#define IDC_EDIT_MOD_NM                 1026
#define IDC_EDIT_THRES_VCB              1026
#define IDC_EDIT_MOD_NO                 1027
#define IDC_STATIC_A_VCB                1027
#define IDC_EDIT_SER_NO                 1028
#define IDC_STATIC_MAX_GRC_PER_VCB      1028
#define IDC_EDIT_FIRM_VER               1029
#define IDC_EDIT_MGP_VCB                1029
#define IDC_STATIC_FRAME                1029
#define IDC_STATIC_SEC_VCB              1030
#define IDC_STATIC_MODEL_NM             1030
#define IDC_FRAME_HIGH_CURR             1031
#define IDC_STATIC_MODEL_NUM            1031
#define IDC_CHK_HIGH_CURR_ENB           1032
#define IDC_EDIT_MNM                    1032
#define IDC_STATIC_THRES_HOLD_HCA       1033
#define IDC_EDIT_MNO                    1033
#define IDC_EDIT_THRES_HCA              1034
#define IDC_STATIC_SER_NUM              1034
#define IDC_STATIC_A_HCA                1035
#define IDC_EDIT_SNO                    1035
#define IDC_STATIC_MAX_GRC_PER_HCA      1036
#define IDC_STATIC_FIRM_VERS            1036
#define IDC_EDIT_MGP_HCA                1037
#define IDC_EDIT_FVERS                  1037
#define IDC_STATIC_SEC_HCA              1038
#define IDC_STATIC_INPUT_CURR_RATE      1038
#define IDC_FRAME_LOW_CURR              1039
#define IDC_EDIT_ICR                    1039
#define IDC_CHK_LOW_CURR_ENB            1040
#define IDC_STATIC_RATED_VOLT           1040
#define IDC_STATIC_THRES_HOLD_LCA       1041
#define IDC_EDIT_RV                     1041
#define IDC_EDIT_THRES_LCA              1042
#define IDC_STATIC_RATED_POW            1042
#define IDC_STATIC_A_LCA                1043
#define IDC_EDIT_RP                     1043
#define IDC_STATIC_MAX_GRC_PER_LCA      1044
#define IDC_STATIC_NO_OF_OUTLETS        1044
#define IDC_EDIT_MGP_LCA                1045
#define IDC_EDIT_NOO                    1045
#define IDC_STATIC_SEC_LCA              1046
#define IDC_STATIC_NO_OF_BANKS          1046
#define IDC_EDIT_NOB                    1047
#define IDC_LIST_BANK_OUTLETS           1048
#define IDC_STATIC_NO_OF_OUTLETS_PER_BANK 1049
#define IDC_STATIC_NUM_OF_INPUTS        1050
#define IDC_EDIT_NOI                    1051
#define IDC_STATIC_FRAME2               1052
#define IDC_STATIC_FRAME3               1053
#define IDC_LIST_LOG                    1054
#define IDC_STATIC_MAIN_TXT             1055
#define IDC_STATIC_COPY_TXT             1056
#define IDC_STATIC_PP                   1057
#define ID_LOG_SELECTALL                32771
#define ID_OUTLET_ON                    32772
#define ID_LOG_DELETE                   32772
#define ID_OUTLET_OFF                   32773
#define ID_LOG_DESELECTALL              32773
#define ID_OUTLET_REBOOT                32774
#define ID_OUTLET_REFRESH               32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
