#ifndef _GEN_DATA_DEFN_61264365544128
	#define _GEN_DATA_DEFN_61264365544128


#define STR_PDU_LOG						_T("DEVICE_LOG")
#define STR_LOG_FILE_NM					_T("DEVICE_LOG.INI")
#define STR_CSV_FILE_NM					_T("DEVICE_DATA.csv")
#define STR_PRG_FILENM					_T("programmed_devices.csv")
#define STR_DEVICE_DETECT				_T("DEVICE_DETECTION")
#define STR_DEVICE_HANDLE				_T("DEVICE_HANDLE")
#define STR_DEVICE_PATH					_T("DEVICE_PATH")
#define STR_DEVICE_VID					_T("DEVICE_VID")
#define STR_DEVICE_PID					_T("DEVICE_PID")
#define STR_PID_VID						_T("PID_VID_STATUS")
#define STR_CLOSE_DEV_HAND				_T("DEVICE_HANDLE_CLOSE")
#define STR_INIT_WRITE_CMD				_T("INITIATE_WRITE_CMD")
#define STR_DEV_DATA_WRTN_BYTES			_T("DATA_WRITN_BYTES")
#define STR_DEV_DATA_READ_BYTES			_T("DATA_READ_BYTES")
#define STR_MAC_ADDR_PREFIX				_T("0009E6")
#define STR_NEXT_LINE					_T("\r\n")
#define STR_UNDERLINE					_T("----------------------------------------------------------------")
#define STR_UNDERLINE_OUTLET			_T("--------------------------------")
#define STR_MOD_NM_EX_SPACE_8			_T("        ")
#define STR_SR_NUM_EX_SPACE_5			_T("     ")
#define STR_MD_NUM_EX_SPACE_6			_T("      ")
#define STR_MAN_DT_EX_SPACE_2			_T("  ")
#define STR_HS_NM_EX_SPACE_9			_T("         ")
#define STR_MAC_EX_SPACE_7				_T("       ")
#define STR_ST_OFF_EX_SPACE_1			_T(" ")
#define STR_OPEN_TITLE					_T("open")
#define STR_PDU_INFO_FILE_NM			_T("DeviceInfo.txt")
#define STR_SPACE_COLON					_T(" :")
#define STR_UNDERSCORE					_T("_")
#define STR_HYPEN						_T("-")
#define STR_EPOWERHD_UNITS				_T("CS_Device_Units.ini")
#define STR_FAIL						_T("FAIL")
#define STR_MONITOR_ONLY				_T("MONITOR_ONLY")
#define STR_FULL_CONTROL				_T("FULL_CONTROL")
#define STR_YES							_T("YES")
#define STR_NO							_T("NO")

#define MAX_PDU_BUFF_SIZE				65
#define MAX_OUTLET_NUM					12
#define ZERO_ID							0x00
#define PDU_STATIC_WRITE				0x81
#define PDU_STATIC_READ					0x82
#define PDU_CONFIG_WRITE				0x83
#define PDU_CONFIG_READ					0x84
#define PDU_STATIC_INFO_MAX				8
#define OUTLET_NM_ID					1
#define OUTLET_24						24
#define OUTLET_16						16
#define MODE_3_PHASE					3
#define MODE_1_PHASE					1
#define MAX_LIST_CTRL					2
#define MAX_MAC_LENGTH					17

#define RES_MINUS_ONE					-1
#define SP_SLASH						_T("\\")
#define SP_BACK_SLASH					_T("/")
#define SP_STAR							_T("*")
#define SP_QUES							_T("?")
#define SP_DB_CODES						_T("\"")
#define SP_SYM_LESS						_T("<")
#define SP_SYM_GREAT					_T(">")
#define SP_SYM_OR						_T("|")
#define SP_SIN_CODES					_T("'")
#define SP_SYM_PLUS						_T("+")
#define SP_SYM_APS						_T("`")
#define SP_SYM_NEG						_T("~")
#define SP_SYM_EXC						_T("!")
#define SP_SYM_AT						_T("@")
#define SP_SYM_HAS						_T("#")
#define SP_SYM_DLR						_T("$")
#define SP_SYM_PERC						_T("%")
#define SP_SYM_UPA						_T("^")
#define SP_SYM_AND						_T("&")
#define SP_SYM_DOT						_T(".")
#define SP_SYM_COMMA					_T(",")
#define SP_SYM_EQUAL					_T("=")
#define SP_EBRACE						_T("]")
#define SP_SBRACE						_T("[")
#define SP_SET_SBRC						_T("{")
#define SP_SET_EBRC						_T("}")
#define SP_SYM_SCOLON					_T(";")
#define STR_COLON						_T(":")

#define STR_HEAD_EPOW_3PHS				_T("EPOWERHD_3PHASE_UNITS")
#define STR_TOTAL						_T("TOTAL")
#define STR_UNIT_NUM					_T("UNIT_%d")
#define STR_TOT_OUTLETS					_T("TOTAL_OUTLETS")
#define STR_TOT_BANKS					_T("TOTAL_BANKS")
#define STR_OUTLETS_PER_BANK			_T("OUTLETS_PER_BANK")
#define STR_UNIT_NM						_T("UNIT_NM")
#define STR_HEAD_EPOW_1PHS				_T("EPOWERHD_1PHASE_UNITS")
#define STR_HEAD_3PHS_INP_CONN			_T("EPOWERHD_3PHASE_INPUT_CONN")
#define STR_HEAD_1PHS_INP_CONN			_T("EPOWERHD_1PHASE_INPUT_CONN")
#define STR_UNIT_NUM_TYPE				_T("UNIT_%d_TYPE")
#define STR_UNIT_NUM_NM					_T("UNIT_%d_NM")
#define STR_HEAD_PM10_3PHS				_T("PM10_3PHASE_UNITS")
#define STR_HEAD_PM10_1PHS				_T("PM10_1PHASE_UNITS")
#define STR_HEAD_PM9S9_3PHS				_T("PM9S9_3PHASE_UNITS")
#define STR_HEAD_PM9S9_1PHS				_T("PM9S9_1PHASE_UNITS")
#define STR_HEAD_3PHS_INP_CONN_PM10		_T("PM10_3PHASE_INPUT_CONN")
#define STR_HEAD_1PHS_INP_CONN_PM10		_T("PM10_1PHASE_INPUT_CONN")
#define STR_HEAD_3PHS_INP_CONN_PM9S9	_T("PM9S9_3PHASE_INPUT_CONN")
#define STR_HEAD_1PHS_INP_CONN_PM9S9	_T("PM9S9_1PHASE_INPUT_CONN")
#define STR_DEVICE_DETAILS				_T("DEVICE_DETAILS")
#define STR_VID_NO						_T("VID_%d")
#define STR_PID_NO						_T("PID_%d")
#define STR_PM10_U_VERS					_T("PM10_U_001")
#define PM10U_MAX_OUTLETS				3
#define STR_HEAD_EPOW_CT_3PH_UNITS		_T("EPOWER_MAN_CT_3PHASE_UNITS")
#define STR_HEAD_EPOW_CT_1PH_UNITS		_T("EPOWER_MAN_CT_1PHASE_UNITS")
#define STR_HEAD_EPOW_CT_3PH_INP_CONN	_T("EPOWER_MAN_CT_3PHASE_INPUT_CONN")
#define STR_HEAD_EPOW_CT_1PH_INP_CONN	_T("EPOWER_MAN_CT_1PHASE_INPUT_CONN")

#define STR_DEV_EPOWER_MAN_CT			_T("DEV_EPOWER_MAN_CT")
#define STR_DEV_EPOWERHD_NM				_T("DEV_EPOWERHD_NM")
#define STR_DEV_PM10_NM					_T("DEV_PM10_NM")
#define STR_DEV_PM10U_NM				_T("DEV_PM10U_NM")
#define STR_DEV_PM9S9_NM				_T("DEV_PM9S9_NM")
#define STR_DELTA_PHS3_ID_1				_T("DELTA_PHS3_ID_1")
#define STR_DELTA_PHS3_ID_2				_T("DELTA_PHS3_ID_2")
#define STR_DELTA_PHS3_ID_3				_T("DELTA_PHS3_ID_3")
#define STR_WYE_PHS3_ID_1				_T("WYE_PHS3_ID_1")
#define STR_WYE_PHS3_ID_2				_T("WYE_PHS3_ID_2")
#define STR_WYE_PHS3_ID_3				_T("WYE_PHS3_ID_3")
#define STR_PHS1_ID_1					_T("PHS1_ID_1")
#define STR_NOT_APP						_T("N/A")

typedef enum _POPUP_DLG_TYPEx
{
	DLG_POPUP_CREATE = 0,
	DLG_POPUP_REFRESH,
	DLG_POPUP_DESTROY
} POPUP_DLG_TYPE;

typedef enum _COLMN_IDx
{
	PDU_MODEL_NM = 1,
	PDU_SERIAL_NUM,
	PDU_MODEL_NUM,
	PDU_MANUFAC_DATE,
	PDU_HOST_NM,
	PDU_MAC_ADDRS,
	PDU_STAGGER_ON_DELAY,
	PDU_STAGGER_OFF_DELAY,
	PDU_FIRMWARE_VERSION,
	PDU_TOTAL_OUTLETS,
	PDU_TOTAL_BANKS,
	PDU_OUTLETS_PER_BANK,
	PDU_PHASE_INP_CONN_TYPE,
	PDU_NETWORK_ENB_DHCP,
	PDU_NETWORK_IP_ADDRS,
	PDU_NETWORK_SUBNET_MSK,
	PDU_NETWORK_DEF_GATEWAY,
	PDU_NETWORK_PRIM_DNS_ADDRS,
	PDU_NETWORK_SECN_DNS_ADDRS,
	PDU_SNMP_READ_COMMUNITY,
	PDU_SNMP_WRITE_COMMUNITY,
	PDU_SNMP_ENB_SNMP_TRAP,
	PDU_SNMP_RECEVR_IP_ADDRS,
	PDU_SNMP_RECEVR_PORT_NUM,
	PDU_EMAIL_ENB_EMAIL_NOTIFY,
	PDU_EMAIL_SMTP_SERVER_ADDRS,
	PDU_EMAIL_SMTP_PORT_NUM,
	PDU_EMAIL_USER_NAME,
	PDU_EMAIL_PASSWORD,
	PDU_EMAIL_RECEVR_EMAIL_ID,
	PDU_GENERAL_SYSTEM_NAME,
	PDU_GENERAL_SYSTEM_LOCATE,
	PDU_GENERAL_SYSTEM_CONTACT,
	PDU_GET_SET_OUTLET_NAME,
	PDU_ALERT_ENB_VCB,
	PDU_ALERT_VCB_MAX_GRAC_PER,
	PDU_ALERT_VCB_THRES_VALUE,
	PDU_ALERT_ENB_LCA,
	PDU_ALERT_LCA_MAX_GRAC_PER,
	PDU_ALERT_LCA_THRES_VALUE,
	PDU_ALERT_ENB_HCA,
	PDU_ALERT_HCA_MAX_GRAC_PER,
	PDU_ALERT_HCA_THRES_VALUE,
	PDU_FACTORY_RESET,
	PDU_PRODUCT_GROUP,
	PDU_BANK_PHASE_ID,
	PDU_CAPACITY,
	PDU_BANK_CAPACITY,
	PDU_OUTLET_CAPACITY,
	PDU_MONITOR_ONLY,
	PDU_FULL_CONTROL,
	PDU_OUTLET_VOLTAGE,
	PDU_OUTLET_FREQUENCY,
	PDU_SET_DATE_TIME,
	PDU_NTP_SETTINGS,
	PDU_NTP_DATE_TIME,
	PDU_SNMP_V3_SETTINGS,
	PDU_NET_SETTINGS,
	PDU_WRITE_OVER
}COLMN_ID;

#pragma pack(1)
typedef	struct	tagTESTx
{
	DWORD	dwInstance;

} TEST, *PTEST;
#pragma pack()

#pragma pack(1)
typedef struct PhaseInfox
{
	char	chePowerManCT[12];
	char	chePowerHDNm[12];
	char	chPM10Nm[12];
	char	chPM10UNm[12];
	char	chPM9S9Nm[12];
	char	chDelta3PhsID_AB[3];
	char	chDelta3PhsID_BC[3];
	char	chDelta3PhsID_CA[3];
	char	chWye3PhsID_AN[3];
	char	chWye3PhsID_BN[3];
	char	chWye3PhsID_CN[3];
	char	ch1PhsID_AN[3];

} PHASE_INFO, *PPHASE_INFO;
#pragma pack()

typedef enum _PDU_DEVICE_TYPEx
{
	DEVICE_EPOWER = 0,
	DEVICE_PM9S9 = 1,
	DEVICE_PM10,
	DEVICE_EPOWER_CT
	
}PDU_DEV_TYPE;

typedef enum _PHASE_ID_SERIES_x
{
	A_SERIES = 1,
	B_SERIES,
	C_SERIES
}PHASE_ID_SERIES;

typedef enum _COLUMN_OUTLET_TABLE_x
{
	COL_OUTLET_CAP = 0,
	COL_OUTLET_NAM = 1,
	COL_OUTLET_VOL,
	COL_OUTLET_FRQ
}COLUMN_OUTLET_TABLE;

typedef enum _OUTLET_ACCESS_FLAG_x
{
	AF_MONITOR_ONLY = 0,		// MONITOR ONLY
	AF_MONITOR_FULL = 1,		// MONITOR ONLY + FULL CONTROL
	AF_FULL_CONTROL,			// FULL CONTROL
}OUTLET_ACCESS_FLAG;


#endif