//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ePower_MFG.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_EPOWER_MFG_DIALOG           102
#define IDS_STR_SYS_INFO_TITLE          102
#define IDS_STR_MODEL_NM_TITLE          103
#define IDS_STR_SER_NUM_TITLE           104
#define IDS_STR_MODEL_NUM_TITLE         105
#define IDS_STR_MANUFAC_DATE_TITLE      106
#define IDS_STR_NETWORK_INFO_TITLE      107
#define IDS_STR_HOST_NM_TITLE           108
#define IDS_STR_MAC_ADDR_TITLE          109
#define IDS_STR_GENERATE_TITLE          110
#define IDS_STR_GENERAL_INFO_TITLE      111
#define IDS_STR_STAGGER_ON_DELAY_TITLE  112
#define IDS_STR_SECOND_TITLE            113
#define IDS_STR_STAGGER_OFF_DELAY_TITLE 114
#define IDS_STR_SAV_SET_DEFAULT_TITLE   115
#define IDS_STR_READ_PDU_TITLE          116
#define IDS_STR_WRITE_TITLE             117
#define IDS_STR_CANCEL_TITLE            118
#define IDS_STR_OUTLET_NM               119
#define IDS_STR_OUTLET_NM_TITLE         120
#define IDS_STR_OUTLET_NO               121
#define IDS_STR_3PHS_TITLE              122
#define IDS_STR_3PHS_INP_CONN_TITLE     123
#define IDS_STR_1PHS_TITLE              124
#define IDS_STR_1PHS_INP_CONN_TITLE     125
#define IDS_STRING126                   126
#define IDS_STR_PDU_NOT_FOUND_MSG       126
#define IDS_STR_NONE                    127
#define IDR_MAINFRAME                   128
#define IDS_STR_P                       128
#define IDS_STR_S                       129
#define IDS_STR_MODEL_NM_ERR_MSG        130
#define IDS_STR_SERIAL_NUM_ERR          131
#define IDS_STR_EPHD_UNIT_ERR_MSG       132
#define IDS_STR_MANUF_DATE_ERR          133
#define IDS_STR_ERR_DATA                134
#define IDS_STR_SUCCESS_MESS            135
#define IDS_STR_PDU_INFO_READ_TITLE     136
#define IDS_STR_FIRMWARE_VER_TITLE      137
#define IDS_STR_TOT_NUM_OUTLETS_TITLE   138
#define IDS_STR_OUTLETS_PER_BANK_TITLE  139
#define IDS_STR_PHS_TYPE_TITLE          140
#define IDS_STR_CONN_TYPE_TITLE         141
#define IDS_STR_OUTLET_NM_TXT           142
#define IDS_STR_HOST_NM_ERR             143
#define IDS_STR_MAC_ADDR_ERR            144
#define IDS_STR_STAG_ON_ERR             145
#define IDS_STR_STAG_OFF_ERR            146
#define IDS_STR_TOT_BANKS_TITLE         147
#define IDS_STRING148                   148
#define IDS_STR_STAG_DELAY_SECS_MSG     148
#define IDS_STR_EPOWER                  149
#define IDS_STR_PM10                    150
#define IDS_STR_3PHS_TITLE_PM10         151
#define IDS_STR_3PHS_INP_CONN_TITLE_PM10 152
#define IDS_STR_1PHS_TITLE_PM10         153
#define IDB_BMP_POPUP                   153
#define IDS_STR_1PHS_INP_CONN_TITLE_PM10 154
#define IDD_DLG_POPUP                   154
#define IDS_STR_SAVE_SETTINGS_MESS      155
#define IDS_STR_BUFFER_SP_ERR           156
#define IDS_STR_CIRCUIT_NM              157
#define IDS_STR_CIRCUIT_TIT             158
#define IDS_STR_CIRCUIT_NM_TIT          159
#define IDS_STRING160                   160
#define IDS_STR_FOLL_CIR_NMS            160
#define IDS_STR_PHASE_INFO_ERR_MSG      161
#define IDS_STR_PHAS_INFO_TIT           162
#define IDS_STR_PROD_GROUP_NM           163
#define IDS_STR_PHS_ID_BANK             164
#define IDS_STR_CAP_PDU_TIT             165
#define IDS_STR_CAP_BANK_TIT            166
#define IDS_STR_CAP_OUTLET_TIT          167
#define IDS_STR_MONITOR_ONLY_TIT        168
#define IDS_STR_3PHS_TITLE_PM9S9        169
#define IDS_STR_3PHS_INP_CONN_TITLE_PM9S9 170
#define IDS_STR_1PHS_TITLE_PM9S9        171
#define IDS_STR_1PHS_INP_CONN_TITLE_PM9S9 172
#define IDS_STR_PM9S9                   173
#define IDS_STR_FULL_CONTROL            174
#define IDS_STR_EPOWER_MAN_CT           175
#define IDS_STR_3PHS_TITLE_EPOW_CT      176
#define IDS_STR_3PHS_INP_CONN_TITLE_EPOWCT 177
#define IDS_STR_1PHS_TITLE_EPOWE_CT     178
#define IDS_STR_1PHS_INP_CONN_TITLE_EPOWER_CT 179
#define IDS_STR_SYS_NM_ERR              180
#define IDC_FRAME_SYSINFO               1000
#define IDC_STATIC_MODEL_NM             1001
#define IDC_STATIC_SER_NO               1002
#define IDC_STATIC_MODEL_NUM            1003
#define IDC_STATIC_MANUFAC_DATE         1004
#define IDC_EDIT_MODEL_NM               1005
#define IDC_EDIT_SER_NUM                1006
#define IDC_EDIT_MANU_DATE              1008
#define IDC_FRAME_NETWORK_INFO          1009
#define IDC_STATIC_HOST_NM              1010
#define IDC_STATIC_MAC_ADDR             1011
#define IDC_STATIC_INFO_PAN             1012
#define IDC_BUTTON_LOAD                 1013
#define IDC_EDIT_HOST_NM                1014
#define IDC_EDIT_MAC_ADDR               1015
#define IDC_BUTN_GENERATE               1016
#define IDC_BUTTON_READ_PDU             1017
#define IDC_STATIC_SECS1                1018
#define IDC_STATIC_SECS2                1019
#define IDC_STATIC_FIRM_VER             1020
#define IDC_LIST_L_OUTLET_NM            1021
#define IDC_STATIC_OUTLETNM_TITLE       1022
#define IDC_FRAME_GEN_INFO              1023
#define IDC_STATIC_STAGGER_ON_DELAY     1024
#define IDC_STATIC_STAGGER_OFF_DELAY    1025
#define IDC_EDIT_STAGGER_ON_DELAY       1026
#define IDC_EDIT_STAGGER_OFF_DELAY      1027
#define IDC_EDIT_FIRM_VERS              1028
#define IDC_EDIT_EPOW_BASE_UNIT         1029
#define IDC_EDIT_EPOW_INP_CONN          1030
#define IDC_LIST_R_OUTLET_NM            1031
#define IDC_STATIC_EPOW_BASE_UINTS      1032
#define IDC_STATIC_EPOW_INP_CONN        1033
#define IDC_COMBO_MODEL_NUM             1034
#define IDC_EDIT_TOT_OUTLETS            1035
#define IDC_EDIT_TOT_BANKS              1036
#define IDC_STATIC_DIV_LINE             1037
#define IDC_COMBO_MODEL_SUB_NUM         1038
#define IDC_STATIC_DIV_LINE2            1039
#define IDC_COMBO_MODEL_NUM_END         1040
#define IDC_STATIC_SELECT_PDU           1041
#define IDC_COMBO_DEVICE                1042
#define IDC_STATIC_POP_PIC              1043
#define IDC_EDIT_OUTLETS_PER_BANK       1043
#define IDC_STATIC_TOT_OUTLETS_TIT      1044
#define IDC_STATIC_TOT_BANKS_TIT        1045
#define IDC_STATIC_OUTLETS_PER_BANK_TIT 1046
#define IDC_STATIC_PDU_DEVICE_CONN_STATUS 1047
#define IDC_EDIT_SYSTEM_NM              1049
#define IDC_STATIC_SYSTEM_NM            1050
#define IDC_STATIC_PDU_DETECT           1051
#define IDC_BUTTON1                     1052
#define IDC_BTN_REFRESH                 1052

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
