//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PDUConfig.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PDUCONFIG_DIALOG            102
#define IDS_STR_NETWORK_SETTING_TITLE   102
#define IDS_STR_SNMP_SETTING_TITLE      103
#define IDS_STR_EMAIL_SETTING_TITLE     104
#define IDS_STR_GENERAL_SETTING_TITLE   105
#define IDS_STR_PDU_SETTING_TITLE       106
#define IDS_STR_OUTLET_NO               107
#define IDS_STR_OUTLET_NM               108
#define IDS_STR_OUTLET_NM_TITLE         109
#define IDS_STR_ALERT_SETTING_TITLE     110
#define IDS_STR_PDU_NOT_FOUND_MSG       111
#define IDS_STR_VALID_NETWORK_IP_ADDRS  112
#define IDS_STR_OUTLET_NUM              113
#define IDS_STR_VALID_SM                114
#define IDS_STR_VALID_SMTP_SER_NM       115
#define IDS_STR_VALID_SMTP_PORT_NUM     116
#define IDS_STR_VALID_EMAIL_USERNM      117
#define IDS_STR_VALID_EMAIL_PASSWD      118
#define IDS_STR_VALID_EMAIL_ID          119
#define IDS_STRING120                   120
#define IDS_STR_VALID_MX_GRC_PER        120
#define IDS_STR_STAG_DELAY_SECS_MSG     121
#define IDS_STR_FACTORY_RESET_PASS      122
#define IDS_STR_FACTORY_RESET_FAIL      123
#define IDS_STRING124                   124
#define IDS_STR_EPHD_UNIT_ERR_MSG       124
#define IDS_STR_VALID_RIP               125
#define IDS_STR_SNMP_SETTINGS           126
#define IDR_MAINFRAME                   128
#define IDD_DLG_NETWORK                 129
#define IDD_DLG_SNMP                    130
#define IDD_DLG_EMAIL                   131
#define IDD_DLG_GENERAL                 132
#define IDD_DLG_PDU                     133
#define IDD_DLG_ALERT                   134
#define IDR_RT_MANIFEST1                135
#define IDD_DLG_POPUP                   136
#define IDB_BMP_POPUP                   139
#define IDD_DLG_SNMP_VER                140
#define IDC_TAB_PDU_CONFIG              1000
#define IDC_BUTTON_CLEAR_ALL            1001
#define IDC_BUTTON_FAC_RESET            1002
#define IDC_STATIC_IP_FRAME             1003
#define IDC_CHECK_DHCP                  1005
#define IDC_STATIC_IP_ADD               1006
#define IDC_STATIC_SUBNET_MASK          1007
#define IDC_STATIC_DEF_GATEWAY          1008
#define IDC_IPADD                       1009
#define IDC_SUBNET_MASK                 1010
#define IDC_GATEWAY_IP                  1011
#define IDC_STATIC_PRIM_DNS             1012
#define IDC_STATIC_SEC_DNS              1013
#define IDC_PRIM_DNS                    1014
#define IDC_SEC_DNS                     1015
#define IDC_STATIC_DNS_SER_ADDR         1016
#define IDC_STATIC_SNMP_READ            1017
#define IDC_STATIC_SNMP_WRITE           1018
#define IDC_EDIT_GEN_SYS_NM             1019
#define IDC_EDIT_SNMP_V3_USER           1019
#define IDC_EDIT_DT_TM_SERVERS          1019
#define IDC_EDIT_GEN_SYS_LOCTN          1020
#define IDC_EDIT_AUTH_PASSKEY           1020
#define IDC_CHECK_SNMP_TRAP             1021
#define IDC_EDIT_LCA_MGP                1021
#define IDC_EDIT_PRIV_PASSKEY           1021
#define IDC_STATIC_SNMP_TRAP_TITLE      1022
#define IDC_EDIT_LCA_THRES_VAL          1022
#define IDC_STATIC_RECEIVER_IP_ADD      1023
#define IDC_EDIT_HCA_MGP                1023
#define IDC_IPADD_TRAP_IP               1024
#define IDC_EDIT_HCA_THRES_VAL          1024
#define IDC_EDIT_GEN_SYS_CONTACT        1025
#define IDC_EDIT_CONF_AUTH_PASSKEY      1025
#define IDC_STATIC_PORT                 1026
#define IDC_EDIT_GEN_STAGGER_ON_DELAY   1026
#define IDC_EDIT_PRIV_CONF_PASSKEY      1026
#define IDC_EDIT_GEN_STAGGER_OFF_DELAY  1027
#define IDC_CHECK_ENABLE_EMAIL          1028
#define IDC_STATIC_EMAIL_SETTING_FRAME  1029
#define IDC_STATIC_SMTP_SERVER          1030
#define IDC_STATIC_SMTP_PORT            1031
#define IDC_STATIC_USER_NAME            1032
#define IDC_STATIC_PASSWORD             1033
#define IDC_STATIC_RECEIVER_EMAIL_ID    1034
#define IDC_EDIT_EMAIL_PASSWORD         1035
#define IDC_EDIT_RECE_EMAIL_ID          1036
#define IDC_STATIC_SYS_NM               1037
#define IDC_STATIC_SYS_LOC              1038
#define IDC_STATIC_SYS_CONTACT          1039
#define IDC_LIST_OUTLET                 1040
#define IDC_STATIC_OUTLET_MESS          1041
#define IDC_EDIT_SNMP_TRAP_PORT         1045
#define IDC_EDIT_SMTP_SERVER            1046
#define IDC_EDIT_SMTP_PORT              1047
#define IDC_EDIT_EMAIL_USER_NM          1048
#define IDC_STATIC_SELECT_PM10_DEV      1049
#define IDC_COMBO_PM10_PDU              1050
#define IDC_CHK_VCB                     1051
#define IDC_STATIC_VCB_SETTINGS         1052
#define IDC_STATIC_VCB_MGP              1053
#define IDC_STATIC_VCB_SECS             1054
#define IDC_STATIC_VCB_THRES_VAL        1055
#define IDC_STATIC_VCB_AMPS             1056
#define IDC_CHK_LCA                     1057
#define IDC_STATIC_LCA_SETTINGS         1058
#define IDC_STATIC_LCA_MGP              1059
#define IDC_STATIC_LCA_SECS             1060
#define IDC_STATIC_LCA_THRES_VAL        1061
#define IDC_STATIC_LCA_AMPS             1062
#define IDC_CHK_HCA                     1063
#define IDC_STATIC_HCA_SETTINGS         1064
#define IDC_STATIC_HCA_MGP              1065
#define IDC_STATIC_HCA_SECS             1066
#define IDC_STATIC_HCA_THRES_VAL        1067
#define IDC_STATIC_HCA_AMPS             1068
#define IDC_EDIT_VCB_MGP                1069
#define IDC_EDIT_VCB_THRES_VAL          1070
#define IDC_STATIC_ALERT_OUTLET_NM      1073
#define IDC_COMBO_OUTLET_NUM_LST        1074
#define IDC_STATIC_STAGGER_ON_DELAY     1076
#define IDC_STATIC_STAGGER_OFF_DELAY    1077
#define IDC_STATIC_POPUP_PIC            1077
#define IDC_STATIC_POPUP                1078
#define IDC_STATIC_SNMP_VERSION         1079
#define IDC_RADIO_SNMP_V2C              1080
#define IDC_RADIO_SNMP_V3               1081
#define IDC_STATIC_SNMP_FRAME           1082
#define IDC_STATIC_SNMP_V3_USER_CAP     1083
#define IDC_STATIC_AUTH_LEVEL           1084
#define IDC_COMBO_AUTH_LEVEL            1085
#define IDC_STATIC_SNMP_AUTH            1086
#define IDC_STATIC_AUTH_PROTOCOL        1087
#define IDC_STATIC_AUTH_PASSKEY         1088
#define IDC_STATIC_CONF_AUTH_PASSKEY    1089
#define IDC_STATIC_SNMPV3_PRIVACY       1090
#define IDC_STATIC_PRIV_PROT            1091
#define IDC_STATIC_PRIV_PASSKEY         1092
#define IDC_STATIC_CONF_PRIV_PASSKEY    1093
#define IDC_STATIC_SNMPV3_READ          1094
#define IDC_EDIT_V3READ_COMNTY          1095
#define IDC_STATIC_SNMPV3_WRITE         1096
#define IDC_EDIT_V3WRITE_COMNTY         1097
#define IDC_STATIC_TELNET_SET           1098
#define IDC_STATIC_HTTP_SETTINGS        1099
#define IDC_STATIC_HTTPS_SETTINGS       1100
#define IDC_CHECK_ENB_TELNET_CONN       1101
#define IDC_CHECK_ENB_HTTP_CONN         1102
#define IDC_CHECK_ENB_HTTPS_CONN        1103
#define IDC_STATIC_NTP_SETTINGS         1104
#define IDC_CHECK_ENB_NTP_DT_TM         1105
#define IDC_STATIC_DAY_TIME             1106
#define IDC_STATIC_NTP_SERVER           1107
#define IDC_STATIC_SET_DT_TM            1108
#define IDC_STATIC_TIME_ZONE            1109
#define IDC_COMBO_TIME_ZONE             1110
#define IDC_STATIC_NOTE                 1111
#define IDC_EDIT7                       1115

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
